<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_License</name>
   <tag></tag>
   <elementGuidId>3e2da05d-cfb0-43e9-8e8a-edd5257ba6bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6465edd6-9531-44df-8cb3-8bbae2650d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03f09961-2987-4dd9-9e40-16e670322f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber</value>
      <webElementGuid>159dc953-9b7c-45cd-8f0b-1e6993a3c510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f2272472-bb3e-4327-b41d-40f311ad2ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>4630ca86-c524-467e-9f5f-18c3061ed3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a4abb268-9ea9-43fd-a4b7-cbbeaba611c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>cae74113-8fe8-4654-90ae-0bbe600c3e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>b977dfbe-de3b-415a-8ce0-ceb15fafa2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>87a742f0-f13f-4261-a276-285178a5f7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber']</value>
      <webElementGuid>b20e1ed5-2b2a-4894-bb88-c51606f2c1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber']/div/input</value>
      <webElementGuid>8ee32359-4f21-46c3-9f37-aa72f4e989e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/div/input</value>
      <webElementGuid>9977beb8-55de-41f2-8ec0-132c447141ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BADriverPopup-BADriverScreen-BADriversDV-LicenseNumber']</value>
      <webElementGuid>1658a21a-b2e4-448f-b32c-40d93e7b1bd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
