<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name</name>
   <tag></tag>
   <elementGuidId>8cf9c760-75a5-47ea-baa0-3605a62ace07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4de6a9f3-9c1a-4414-84b6-b2e8be565a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fb6f90d-5f89-47da-b011-a94c24324201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName</value>
      <webElementGuid>e1165249-220d-49f1-b37b-33d70a603237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b404626-9b76-4ee5-ae61-12690a45603f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>d4ff0ae7-a1c8-4df8-9974-a537bc555280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>b45590ad-a0ea-4a3d-b87a-5df1f581b660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>23d39802-fbe4-48a8-adbd-b834f03cc44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>b83f2035-8d57-49fa-8946-565d8c46affa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>73e43422-f1b4-4b2c-8ef7-9dc8bfae4621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName']</value>
      <webElementGuid>4abfff3c-2fff-4b3c-b4a5-8a312ad5968a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName']/div/input</value>
      <webElementGuid>2a92f700-828e-4aa4-acf2-d631594373cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>aaa753df-ce13-4bf1-888f-24858e48f053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-FirstName']</value>
      <webElementGuid>6ced945b-0ea7-4d6a-a9fe-e665c0cc74ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
