<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth</name>
   <tag></tag>
   <elementGuidId>61b5b250-c1c8-4398-816e-36094fa08755</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Date of Birth&quot;i >> internal:attr=[placeholder=&quot;MM/dd/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df67c6f3-9fac-459f-b94f-561933d69f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08e7c312-1ca0-4093-a364-35ae45b367de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-min-visible gw-DateValueWidget--dateInput gw-focus</value>
      <webElementGuid>45a3eea4-c87a-4243-bbe9-2dba8d1caefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth</value>
      <webElementGuid>ab0fe9e9-baee-4e8f-b4c6-efbb401cba5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26ecc19a-4348-4a4f-8b33-7c5a7cea30b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/dd/yyyy</value>
      <webElementGuid>6411a176-bae2-4bfb-9658-434137191530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>date input</value>
      <webElementGuid>017c2bfa-6301-4d28-85b7-7c2af185beb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-focus</name>
      <type>Main</type>
      <value>gwDateValue.showDatePickerOnFocus</value>
      <webElementGuid>4c3863c5-c34e-4a17-a961-305fd495619d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>39f64ad8-ecc9-431c-928c-0dfe02e6307b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>93ace527-4084-4804-9e88-c9a968d1ae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e4cee64e-0a40-4cf0-a91f-112be7ddec01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-min-visible gw-DateValueWidget--dateInput gw-focus&quot;]</value>
      <webElementGuid>4a8bf266-5ab2-4008-9424-fffbfe7f1fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth']</value>
      <webElementGuid>11376ddb-249f-4ed8-a62b-d0fc86352f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth']/div/input</value>
      <webElementGuid>f93c5d9c-a4a3-4de3-a4a9-4a62b4774c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div/div/input</value>
      <webElementGuid>413b7236-b64e-4abc-9804-1424a928c218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BADriverPopup-BADriverScreen-BADriversDV-DateOfBirth' and @placeholder = 'MM/dd/yyyy']</value>
      <webElementGuid>3e84587f-0d88-4ecf-a204-1daf505e798a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
