<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name</name>
   <tag></tag>
   <elementGuidId>3ebfa4fd-bf67-4c26-afe4-f37f88ab0640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d8aa9a9-5ef5-4188-9d05-65d40df42ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97e3a917-b17c-4693-aead-981dda59263d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName</value>
      <webElementGuid>455041f7-586e-42b1-8d21-571fd81ca985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1d5945ab-7fc1-4b1f-a266-fa664af36d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>e812853f-c84c-4dec-8b9e-de3e67ec30bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>64c9e535-ffbc-4c35-955b-274240b923eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>c09566f5-7036-4d2d-a963-cd3d0400b9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>c564d484-c1f2-4dc4-abce-07d2aafec5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>f2aec467-5a07-4d6c-9475-5ef7e2c6732f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName']</value>
      <webElementGuid>6189f7d6-67ec-40c8-92b2-ccec6d275110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName']/div/input</value>
      <webElementGuid>15f58149-37a0-4ca8-9c2a-a20ebe0f11e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>beaea7ae-4f3c-48af-b00d-a3f3ea7a9edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BADriverPopup-BADriverScreen-BADriversDV-GlobalPersonNameInputSet-LastName']</value>
      <webElementGuid>b42e988f-7673-40eb-887b-d313862c9d4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
