<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_state</name>
   <tag></tag>
   <elementGuidId>60132689-a372-4b4d-87b2-5dfe40511572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='BADriverPopup-BADriverScreen-BADriversDV-LicenseState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseState&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseState&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43e0fc0e-0908-4139-9a18-70e243783aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BADriverPopup-BADriverScreen-BADriversDV-LicenseState</value>
      <webElementGuid>ea794609-73d6-4fba-8bfa-b778e45e79b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1ca53c9c-45fb-4ff0-bb39-465a541c3a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>55d6436d-8fef-47fc-a5ca-dd8c6ee0bdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>HokkaidoAomoriIwateMiyagiAkitaYamagataFukushimaIbarakiJervis Bay TerritoryTochigiGummaSaitamaChibaTokyoKanagawaNiigataToyamaIshikawaFukuiYamanashiNaganoGifuShizuokaAichiMieShigaKyotoOsakaHyogoNaraWakayamaTottoriShimaneOkayamaHiroshimaYamaguchiTokushimaKagawaEhimeKochiFukuokaSagaNagasakiKumamotoOitaMiyazakiKagoshimaOkinawaA.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   </value>
      <webElementGuid>c1660c7c-71e4-40a4-b47e-8dbcd685c532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BADriverPopup-BADriverScreen-BADriversDV-LicenseState&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>c12e2770-a0f7-40af-9b10-38e3b4495f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='BADriverPopup-BADriverScreen-BADriversDV-LicenseState']</value>
      <webElementGuid>335808bb-27e7-473c-9908-d36db0dd8cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BADriverPopup-BADriverScreen-BADriversDV-LicenseState']/div/div/select</value>
      <webElementGuid>743ce4bd-d6ec-4937-9053-c94de9ff0dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License State'])[1]/following::select[1]</value>
      <webElementGuid>737723ce-e99b-4a66-989d-11066699337a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License #'])[1]/following::select[1]</value>
      <webElementGuid>38b5d8c9-e648-411e-a959-920e17310d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Year'])[1]/preceding::select[1]</value>
      <webElementGuid>9fa6e967-2677-40d7-9514-8c952c8d5e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hire Date'])[1]/preceding::select[1]</value>
      <webElementGuid>f978238a-854e-41d0-ad4c-7213b0316002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/div/div/select</value>
      <webElementGuid>b296cccf-2e9b-43b9-9128-77c8214c032b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'BADriverPopup-BADriverScreen-BADriversDV-LicenseState' and (text() = '   &lt;none>HokkaidoAomoriIwateMiyagiAkitaYamagataFukushimaIbarakiJervis Bay TerritoryTochigiGummaSaitamaChibaTokyoKanagawaNiigataToyamaIshikawaFukuiYamanashiNaganoGifuShizuokaAichiMieShigaKyotoOsakaHyogoNaraWakayamaTottoriShimaneOkayamaHiroshimaYamaguchiTokushimaKagawaEhimeKochiFukuokaSagaNagasakiKumamotoOitaMiyazakiKagoshimaOkinawaA.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   ' or . = '   &lt;none>HokkaidoAomoriIwateMiyagiAkitaYamagataFukushimaIbarakiJervis Bay TerritoryTochigiGummaSaitamaChibaTokyoKanagawaNiigataToyamaIshikawaFukuiYamanashiNaganoGifuShizuokaAichiMieShigaKyotoOsakaHyogoNaraWakayamaTottoriShimaneOkayamaHiroshimaYamaguchiTokushimaKagawaEhimeKochiFukuokaSagaNagasakiKumamotoOitaMiyazakiKagoshimaOkinawaA.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   ')]</value>
      <webElementGuid>3d235d32-1e87-4ac4-9198-e058154a58db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
