<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SelectClassCode</name>
   <tag></tag>
   <elementGuidId>e29ef8ec-fffc-41d8-a1aa-96676851fd08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search...&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>661b329f-76d7-40e6-981a-225827905039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode</value>
      <webElementGuid>eb00a3cf-36de-4bea-9789-ee97fce11c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-ImageButtonWidget gw-styleTag--ValueWidget gw-picker-button gw-focus</value>
      <webElementGuid>39520463-911d-4a6c-a6dd-cd6e508028ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>6237553b-abad-4a12-92bb-338082bba7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-tooltip</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>d59aaea3-0263-40a3-ba7d-21c6a0389d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>4a6d9900-9cb8-438f-89e8-40095c6913c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>63e214c9-968e-4259-84cd-e2d10b5b3833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseenter</name>
      <type>Main</type>
      <value>gwMouse.enter</value>
      <webElementGuid>1c82fc4e-24b2-4df9-bbe0-ccac78cda671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mousemove</name>
      <type>Main</type>
      <value>gwTooltips.move</value>
      <webElementGuid>544db67e-d734-492c-adde-4afd0fb84528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseout</name>
      <type>Main</type>
      <value>gwTooltips.hide</value>
      <webElementGuid>7a8481e5-2589-4469-9c5f-7400084c276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseover-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ef3446a-53e1-459b-8917-1342a368b666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseout-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9c4793d-2fa7-41f8-89b0-b81cda5c7bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mousemove-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8014e177-154e-4054-8496-d8399e48974e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-mouseenter-enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22cab4c0-3964-4d72-9273-1e8486831a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dbd86537-99e8-4fc4-b259-34414435ac37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode&quot;)</value>
      <webElementGuid>9af4b3e4-3895-42e0-be2e-915d3fe57780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode']</value>
      <webElementGuid>cfa15076-6600-445b-b92d-14427bd17f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode']/div[2]/div</value>
      <webElementGuid>2d678a66-abe2-4ab4-9871-ab4b8ab780a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/following::div[5]</value>
      <webElementGuid>307d6f37-2e68-4a2d-9f7f-cad1755c0d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classification Information'])[1]/following::div[8]</value>
      <webElementGuid>0a0e6863-1237-4043-8572-1b5a0da2fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Rate Modifiers'])[1]/preceding::div[6]</value>
      <webElementGuid>7d890d23-111c-478c-bddf-fa4b8aacc61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Vehicle Additional Interests'])[1]/preceding::div[11]</value>
      <webElementGuid>327537bd-a8aa-4891-8b11-b0626267da75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/div/div[2]/div</value>
      <webElementGuid>8721d2e8-10c9-481c-b2b4-3e743edd1d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode-SelectClassCode']</value>
      <webElementGuid>8f616611-ebcb-4a3b-b9b9-6b877a0b0e94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
