<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Class_SelectClassCode</name>
   <tag></tag>
   <elementGuidId>9d7417c8-25e3-4dbd-a673-910917a3e981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fca162ee-8c71-4d8c-b376-4632fae8a076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6003897b-d9c3-4986-9b50-31c9f0e967ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode</value>
      <webElementGuid>6f605ac1-811b-4893-b9c6-c7cbea7aa54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-picker-input gw-focus</value>
      <webElementGuid>707c8403-d6d7-4c53-8efc-b05e64a0c189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e305810-17e7-46f6-baec-4c6c7752430f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5c948894-8566-418e-a7ed-6aad947d6f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>d8d04990-1847-488a-a34c-0bccbe52fd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>8f1eeac1-7fc9-4f4d-8075-49d7f022bc31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-picker-input gw-focus&quot;]</value>
      <webElementGuid>6a6d546f-34f6-42b6-b725-b2344a0e1870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode']</value>
      <webElementGuid>6c122ef2-27fd-4d0a-9fd9-45415ed50269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode']/div/input</value>
      <webElementGuid>c2f27aea-dfc1-4142-8908-f7a77b81e92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/div/div/input</value>
      <webElementGuid>caaa2378-cdda-4d0f-a753-07c551765ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-ClassCode']</value>
      <webElementGuid>986d1a2a-216f-464b-afa1-f1b5c2d6dd3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
