<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cost</name>
   <tag></tag>
   <elementGuidId>6066c3d5-1e01-44a0-acaa-0311e7d02bbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cost&quot;i >> internal:label=&quot;$&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c3c6a47-d482-4c88-95bd-52f9190a043b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40177533-e30f-4152-87d9-4ba9ab1f4e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-currency-info</name>
      <type>Main</type>
      <value>USD;$;,;.;2</value>
      <webElementGuid>65f13ae9-d574-4d58-8cba-b7bbc3cc87a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost</value>
      <webElementGuid>0420573e-bda2-4500-a283-40f7f2b40458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48b24d19-1399-4a83-b5d0-68c43f937464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>59634d33-b1a8-496c-9e54-e6070968a327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>723cf6ec-8e30-4c43-9844-6dbc4c9f28cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>$ </value>
      <webElementGuid>04c97d12-c506-4dc8-bd30-b7465e086ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>8a56c088-4fee-4711-b476-0e29c3c1e3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>552085d2-21dc-405a-90a3-4fe707f998f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost']</value>
      <webElementGuid>c335dce0-39e7-4a9d-bfc1-5471f9c08569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost']/div/input</value>
      <webElementGuid>ad011ec8-19cc-4fad-9f90-976200172d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/div/div/input</value>
      <webElementGuid>6a726704-586d-43c7-8d84-553193ef8b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Cost']</value>
      <webElementGuid>db65958d-fb34-4c49-a515-52e6c3be3fa3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
