<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIN</name>
   <tag></tag>
   <elementGuidId>d0c44fb1-b519-4b52-85b8-1e2763dd9592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba015c7f-d04a-448c-9625-0903679d4d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b146e4c7-7cfd-4762-bd64-3dc136e3c6cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin</value>
      <webElementGuid>661bc797-7bb1-4677-8946-abef6a9f24d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fedd999e-88a4-4eaa-8f34-01ad923cf3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>b3821ea2-d6db-4678-9799-cbdaf05555d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>88015b12-d566-4cb5-b7c3-e33efb4c7587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>01695084-df91-4cf6-8211-9992714d3efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4cb7dbd8-93f9-4a43-84a2-ebf3c145acdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>c2193f7a-c7a8-4266-94af-b50f21f4540a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin']</value>
      <webElementGuid>474a0705-f48e-4c84-8afe-3481860e12f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin']/div/input</value>
      <webElementGuid>e96e5880-73f6-4da5-ab68-8068862b48d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>536fe6c6-853d-42b4-8240-653c008e0990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Vin']</value>
      <webElementGuid>de193a79-5167-4e2f-ba6b-978746e88416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
