<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Garaged at</name>
   <tag></tag>
   <elementGuidId>b55db041-4a86-4627-b97d-772baed04318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e38a44d9-993a-41ca-bbe5-f07f7a1ef2d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput</value>
      <webElementGuid>3f7943d0-dbb2-4bba-81cf-31b4ff19388a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>884ffc1b-e594-4d51-8f13-3ca2be820a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3412ebc7-7346-44f0-912e-110ca781b683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>    1: 3449 Morgan ave, Corpus Christi, TX   </value>
      <webElementGuid>e03179c0-6267-46ba-a8ae-b425f3368429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>fa1a680d-560e-49a8-9f60-9e5baab1ad5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput']</value>
      <webElementGuid>ad960db4-c21e-4dcb-994e-a1de52ed84fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput']/div/div/select</value>
      <webElementGuid>b710330b-4801-46c1-9149-bc233d2ff735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garaged At'])[1]/following::select[1]</value>
      <webElementGuid>04339833-8e53-4d93-bd10-22765c9e74fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Coverages'])[1]/following::select[1]</value>
      <webElementGuid>084b7bf2-3c5c-42db-bd50-97fad1185074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NL'])[1]/preceding::select[1]</value>
      <webElementGuid>fd8073f6-28ae-4af9-ab36-10e4701fe0ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Location'])[1]/preceding::select[1]</value>
      <webElementGuid>e4614f6b-46ca-4a45-91f8-f229123f9a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f93b0dba-f2b9-4a3a-955f-8094e82dc632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-BAGarageLocationInputSet-BAGarageLocationInput' and (text() = '   &lt;none>    1: 3449 Morgan ave, Corpus Christi, TX   ' or . = '   &lt;none>    1: 3449 Morgan ave, Corpus Christi, TX   ')]</value>
      <webElementGuid>0a454c5b-f532-4266-be3b-97a54f3f142d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
