<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VehicleType</name>
   <tag></tag>
   <elementGuidId>68f7c386-fc90-4d6b-97d0-acf3bd98211d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f951295-b4e2-4782-997e-0f692c0d2e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type</value>
      <webElementGuid>52aa3fa2-651d-4393-b45b-73ae45db0b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cbb330cd-0343-4849-b037-31764b26e64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>3a207667-5db1-48cc-a8ba-857483f1cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Trucks,Tractors,TrailersPassenger VehiclesLivery VehiclesSpecial   </value>
      <webElementGuid>a7b54544-c3fe-4df6-b521-e5fbd78d8c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>05e7d0f4-2e47-4930-b03c-f5fd7636965f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type']</value>
      <webElementGuid>6e71c2b8-5f4f-4e1a-b83d-8c6a59446ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type']/div/div/select</value>
      <webElementGuid>ef295900-fc78-42f9-8d5b-cb5e14e8d1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Type'])[1]/following::select[1]</value>
      <webElementGuid>c932761d-86f3-4eb7-8ed8-28c757fefb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle #'])[1]/following::select[1]</value>
      <webElementGuid>03161e99-438e-47fb-ba52-64408c18b6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN'])[1]/preceding::select[1]</value>
      <webElementGuid>0377aa15-6a33-481c-ae22-6911d08775f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Year'])[1]/preceding::select[1]</value>
      <webElementGuid>78be24c3-81a1-4bf9-9697-ad9b3242281e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/select</value>
      <webElementGuid>f1bed1e9-22c1-42f5-ae91-14a10e58b2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'BAVehiclePopup-VehicleScreen-BAVehicleCV-VehicleDV-Type' and (text() = '   &lt;none>Trucks,Tractors,TrailersPassenger VehiclesLivery VehiclesSpecial   ' or . = '   &lt;none>Trucks,Tractors,TrailersPassenger VehiclesLivery VehiclesSpecial   ')]</value>
      <webElementGuid>1db7b9d3-042b-4100-a292-7c9cc259f020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
