<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PolicyNumber_Search</name>
   <tag></tag>
   <elementGuidId>7d6a0691-c014-48e9-af7a-8acef0f4e1fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ee56342-97db-4891-aa97-a4c08b4467a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b183c8f4-601e-4dfa-85da-52dd18ff1aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem</value>
      <webElementGuid>4f68d8d5-6352-40a9-81ed-a5d5db051544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39ebf703-ff9f-42e9-8cb6-3b5d196cf892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>a5235a84-aaaf-4784-a7da-75e33fabf894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>68a17b4e-cd50-46f7-89fd-116b0b6dafc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>6e6c0bde-689b-4d1b-891e-cf21ddebac35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>e0f4bcf0-e1df-4682-9fb1-79c49b38977e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>87a38cae-7d12-475f-a190-067a4e1aa5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem']</value>
      <webElementGuid>d0480087-36cd-4c1e-8438-a6d41348ee1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem']/div/input</value>
      <webElementGuid>5d3e40ac-9a90-4b74-85dc-a9c64305d23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>9c43a1b7-c849-47da-925d-201e6a3e97dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TabBar-PolicyTab-PolicyTab_PolicyRetrievalItem']</value>
      <webElementGuid>f7e158dc-8973-4fa4-97d7-c5a82d1013d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
