<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Risk Analysis</name>
   <tag></tag>
   <elementGuidId>99c2616d-426a-403b-9044-8968fa14f492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-Job_RiskAnalysisScreen-0']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-TitleBar--title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Risk Analysis&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5afefc9b-287b-43f6-9197-3e2b8f9bc3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-TitleBar--title</value>
      <webElementGuid>53867336-87ed-4ea7-9638-5b2047253eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>b1b4190c-9110-4297-b6b3-d8a661355206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>289028c7-148f-4027-8b60-da87c172d538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Risk Analysis</value>
      <webElementGuid>fd34f62c-6585-46bd-bc94-e22aa74d0498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-Job_RiskAnalysisScreen-0&quot;)/div[@class=&quot;gw-TitleBar--titles--container&quot;]/div[@class=&quot;gw-TitleBar--title&quot;]</value>
      <webElementGuid>ad7809af-bb3f-447f-be64-4a6a98630d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-Job_RiskAnalysisScreen-0']/div/div</value>
      <webElementGuid>f237fd12-9566-4e50-9a50-45ed6bdc7770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Christine Craft'])[1]/following::div[5]</value>
      <webElementGuid>0decdee3-e7b1-4564-b7f4-2fd0acdf251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter:'])[1]/following::div[6]</value>
      <webElementGuid>90aeefa8-26af-4836-b060-f4ecddc60f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ba'])[1]/preceding::div[3]</value>
      <webElementGuid>a58a05b6-4298-462b-a023-47c0c20cebe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[5]</value>
      <webElementGuid>0a02e599-06d0-40fb-89b8-57454a1fd7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div/div</value>
      <webElementGuid>003e4162-a492-4c18-928d-fe03e99e9a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Risk Analysis' or . = 'Risk Analysis')]</value>
      <webElementGuid>d5db2bfa-33ff-48e0-b2a5-32929dbb89f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
