<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_The search returned zero results</name>
   <tag></tag>
   <elementGuidId>e62dcdb0-a5d4-4697-8afa-a93c7ebb96aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewAccount-NewAccountScreen-_msgs-0-0']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;The search returned zero results.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fc693d1-7bd9-4134-987a-f3b439bda9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-message</value>
      <webElementGuid>74a32439-cedd-4694-9b33-f9391bb1dc1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The search returned zero results.</value>
      <webElementGuid>7db5a241-7d48-4fb4-998e-ff70e6d7f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewAccount-NewAccountScreen-_msgs-0-0&quot;)/div[@class=&quot;gw-message-and-suffix&quot;]/div[@class=&quot;gw-message&quot;]</value>
      <webElementGuid>236421bc-bda8-4f1a-b38c-8068a17c02dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewAccount-NewAccountScreen-_msgs-0-0']/div[2]/div</value>
      <webElementGuid>5fd52578-aa7c-400e-bf0d-330b20bd6d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information for the current page:'])[1]/following::div[6]</value>
      <webElementGuid>bd79fa8c-283c-4959-90c0-89542047ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Account Information'])[3]/following::div[16]</value>
      <webElementGuid>58dad8c3-428d-40d2-a381-2509be8aff9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Applicant Information'])[1]/preceding::div[3]</value>
      <webElementGuid>d9468ff4-2f23-4f41-90d3-7921c2f8679f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Name'])[1]/preceding::div[6]</value>
      <webElementGuid>59232284-8d19-40bc-bdc9-a59baa389323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The search returned zero results.']/parent::*</value>
      <webElementGuid>9ff303f8-74bf-4cd7-a304-a84cfccb2032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[2]/div</value>
      <webElementGuid>18906473-074b-47fc-af08-926f3055c70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'The search returned zero results.' or . = 'The search returned zero results.')]</value>
      <webElementGuid>ff2f74d7-4421-40cb-be06-60750a9fac64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
