<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exclude Pollution - Except Heating Equip Hostile Fire_Checkbox</name>
   <tag></tag>
   <elementGuidId>b4791b41-373e-49f1-a166-0b4ecac163bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;select row Exclude Pollution - Except Heating Equip &amp; Hostile Fire POLLUTION Exclusion&quot;i] >> internal:label=&quot;select row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86827616-8afd-449a-a6ff-66661117d3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0bc04f04-03e5-4e7e-bb5f-8600b7aa7a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bfda2b25-fea8-421b-8734-ac552648ad2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox</value>
      <webElementGuid>02945361-071d-4e3b-b253-1d47c222619f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV</value>
      <webElementGuid>34990ec2-c237-4388-a714-470e8cd1c28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>CoveragePatternSearchResultsLV,-</value>
      <webElementGuid>2eea74ff-68ff-4156-a1e3-43ec75f38854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select row</value>
      <webElementGuid>c9035250-156a-4b2d-a92c-688a04d96854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>b322d8a7-ba5b-40f3-9c63-bb36dedf6e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>55b2a97d-6cc8-4f22-a939-cd36343d3e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox']</value>
      <webElementGuid>6384352c-bc32-4757-9f2b-b3b4c736add8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox']/input</value>
      <webElementGuid>a88c8551-bff2-442d-9d37-77c92eec1017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/input</value>
      <webElementGuid>0c4e930b-751e-4a75-8dfa-665dd695161c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-1-_Checkbox']</value>
      <webElementGuid>b46d0ebc-eab7-44d8-96dc-d83626fb6bd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
