<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exclude Pollution - Except Hostile Fire_Checkbox</name>
   <tag></tag>
   <elementGuidId>b92f9284-8c61-4aa8-969b-eaa3cd3fb8a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;select row Exclude Pollution - Except Hostile Fire POLLUTION Exclusion&quot;i] >> internal:label=&quot;select row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>edae9017-f15a-4475-8261-2403236e1cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3647a2b9-2222-4a97-a934-d49c65cca846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>afab0ccf-e4f7-4707-bf11-fb6dd5c9989f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox</value>
      <webElementGuid>44dc2684-3312-462b-8d0b-138379055b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV</value>
      <webElementGuid>80014a1e-6201-4356-b241-0511319595f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>CoveragePatternSearchResultsLV,-</value>
      <webElementGuid>593fd65c-c849-4d97-bd70-d73d6218900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select row</value>
      <webElementGuid>b2c39fd6-94eb-4058-b58a-27d082562db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>a99eca0e-75cc-491b-9cb6-76943d6eb943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>bdc4f73f-d0df-4579-9854-e2a0e33294f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox']</value>
      <webElementGuid>b206555b-cb85-4081-8bfb-cb253e412983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox']/input</value>
      <webElementGuid>3a00f29c-3ab4-4ee2-b076-858c7be1154b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/div/input</value>
      <webElementGuid>95aa812e-88fb-481d-a6f9-0ee92217f6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-2-_Checkbox']</value>
      <webElementGuid>c16f33f5-eee3-4798-90c9-e00519124a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
