<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Property class code search icon</name>
   <tag></tag>
   <elementGuidId>e47b624d-332e-4b00-b3a1-0255dc386d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-Actions-ActionsMenuIcon']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;options&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1f97c6bf-4299-4871-90bd-d8ddc6cbb91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f207d1e-17b6-40bd-a512-4833728c2385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-action--inner gw-focus</value>
      <webElementGuid>c2a8819a-2491-4a36-9bc4-5bf242e1bb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>options</value>
      <webElementGuid>2be5ea72-7309-4d08-8950-c6a6b2f6c230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>151a069d-aaf6-4c58-8a70-32a79f6ad192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5781950e-dd38-4314-8da2-39f4efc8a73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>39b8d549-b005-4eb4-8ed8-52eaabfb82e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>toggleSubMenu</value>
      <webElementGuid>df007346-62af-4202-8005-08e6c7ec3bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4f1c26f-c1d5-4406-a6bb-e92bb2c0e4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-Actions-ActionsMenuIcon&quot;)/div[@class=&quot;gw-action--inner gw-focus&quot;]</value>
      <webElementGuid>518e74b0-df18-4125-837f-7fd0a40f00a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-Actions-ActionsMenuIcon']/div</value>
      <webElementGuid>2ed03a59-e4eb-4be7-873d-02f9706eb9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extra Expense Limit'])[1]/following::div[11]</value>
      <webElementGuid>3a4f05c9-fef7-48a3-b1e8-76065529600c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Income Limit'])[1]/following::div[16]</value>
      <webElementGuid>637513e4-5bbd-432e-b3f0-ee2c3c18549b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AB'])[1]/preceding::div[4]</value>
      <webElementGuid>d0f60736-21b2-4cf6-952e-ea7fbf33ec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Building'])[1]/preceding::div[6]</value>
      <webElementGuid>020f82d9-2c56-4049-90dd-1c20ef30b131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div[2]/div/div</value>
      <webElementGuid>6a8fa70f-ba4b-41dd-81ed-54009806d0b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
