<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_default location</name>
   <tag></tag>
   <elementGuidId>fd83bd90-a168-42b7-bbb8-b85d21319d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;1: 3449 Morgan ave, Corpus Christi, TX (Primary)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8c3ddb0-aabb-442b-bd50-f07d66a946d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3456f2ee-3667-4777-9b9c-b82eeb0da997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-ActionValueWidget gw-focus</value>
      <webElementGuid>c76dba11-08f2-474f-bb3c-a52461fae90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button</value>
      <webElementGuid>45dfcdbf-bebc-405a-b2fc-faf08daa9ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent id:SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName</value>
      <webElementGuid>6198a529-e5b7-494f-8ad8-9cb3977e6e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3c3b1e6-d4a5-4af1-84c4-a464ecdf5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1: 3449 Morgan ave, Corpus Christi, TX (Primary)</value>
      <webElementGuid>2f6d6918-a515-4bcf-8141-4040716ec433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button&quot;)</value>
      <webElementGuid>442e8954-99d4-4648-ac59-8a8b6099f87f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button']</value>
      <webElementGuid>ed6f9892-f352-48ee-b3cd-e74ef0307be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName']/div/div</value>
      <webElementGuid>e04b4248-e4a3-41ef-a6f6-7d24f296ba28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Building'])[1]/following::div[5]</value>
      <webElementGuid>ef69e2cd-e1fe-482b-964c-5c0e0695262c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NB'])[1]/following::div[6]</value>
      <webElementGuid>26ab3243-6036-458f-8afe-34703ce6cc6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1: 3449 Morgan ave, Corpus Christi, TX (Primary)']/parent::*</value>
      <webElementGuid>0625fae0-179f-4427-a0e6-8c572472589d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/div/div</value>
      <webElementGuid>9b3bea2a-ac19-4ecb-97f4-eb88f8a39106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-CPBuildingsScreen-CPBuildingsAndLocationsLV-0-LocationName_button' and (text() = '1: 3449 Morgan ave, Corpus Christi, TX (Primary)' or . = '1: 3449 Morgan ave, Corpus Christi, TX (Primary)')]</value>
      <webElementGuid>cb81eb47-0942-4978-9249-e66bfe61b794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
