<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_State Info</name>
   <tag></tag>
   <elementGuidId>bd696f04-e522-4d4f-a683-5fe9a6c03bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BAStateInfoScreen-ttlBar']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-TitleBar--title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;State Info&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04ece5f2-c5eb-4885-9642-9789d447880b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-TitleBar--title</value>
      <webElementGuid>e94b3d3e-0f21-42f8-8baf-9590dd38c209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>28ce186f-b3d9-45fb-9220-75f43f01aa70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef4d4fb3-7461-4f38-bf93-48999a534ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State Info</value>
      <webElementGuid>857633c1-806d-4e8d-a721-1a557635e287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BAStateInfoScreen-ttlBar&quot;)/div[@class=&quot;gw-TitleBar--titles--container&quot;]/div[@class=&quot;gw-TitleBar--title&quot;]</value>
      <webElementGuid>f2460bd9-0e94-4140-996b-9fa46150a4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BAStateInfoScreen-ttlBar']/div/div</value>
      <webElementGuid>53571786-19c0-42e2-a7a5-7bc083c42418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steve Smith'])[1]/following::div[5]</value>
      <webElementGuid>2934c265-f7f1-462c-a535-6f50054bb4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter:'])[1]/following::div[6]</value>
      <webElementGuid>84809832-1fce-4ee3-8ebc-6933afbd9e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ba'])[1]/preceding::div[3]</value>
      <webElementGuid>acde0f17-b9f1-4fec-8658-b977e353b1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[5]</value>
      <webElementGuid>b649df9c-28fd-4057-9e9b-a0ea1cf149da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div/div</value>
      <webElementGuid>3de085fc-26aa-4e61-871a-609873a80a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'State Info' or . = 'State Info')]</value>
      <webElementGuid>e00e6bd6-b2da-4112-9174-0db1589e1bdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
