<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>9ddc358f-9c5f-4b98-bf7c-612efc4e3568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Select&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e00de2d0-ee1e-41b8-a3f3-7a7b31516265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton</value>
      <webElementGuid>664497d7-3476-48ed-b418-c00e05c87eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>cd910fe0-ae13-496e-b2e3-73021dbd8a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>9d8ab7c7-a815-4abc-ab9d-a9b67b991a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-shortcut</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton&quot;,&quot;key&quot;:&quot;e&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;S&quot;}</value>
      <webElementGuid>c954dedd-3182-4f4f-8946-2a4b2f9dd8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>811abac6-2196-41df-9083-ed8ed55ff256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98a3452c-8162-4813-b304-7c6a92f984af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>67ccf8e3-8950-4129-a44f-ef754387a2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton&quot;)</value>
      <webElementGuid>c2ddfdb1-0aca-45f5-bd88-d9aaa8f030aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton']</value>
      <webElementGuid>b5fc492b-8cad-416b-ad01-737291050e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-Select']/div/div/div</value>
      <webElementGuid>5e03889d-680e-4fd7-9183-e39e951273f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[4]/following::div[11]</value>
      <webElementGuid>2c46b10e-1486-4dbb-bcb0-7476d37020aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[3]/following::div[18]</value>
      <webElementGuid>7f70dfaf-8c60-4018-b10d-0e9c15dcd38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PolicyManuscriptFreeFormRev1'])[1]/preceding::div[8]</value>
      <webElementGuid>37f8b771-cc65-4be5-9c90-1e716e0d74da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div/div/div[2]/table/tbody/tr[2]/td[2]/div/div/div</value>
      <webElementGuid>5a38d4b2-71ed-4ceb-89e4-1e4892dadbaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearchResult_AccLV-0-selectButton' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>9353fe29-b2d0-466c-81fd-78501d5c4ff1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
