<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Coverage for injury to leased Workers_Checkbox</name>
   <tag></tag>
   <elementGuidId>4868696b-9fed-42be-bf7c-31516ce1f0f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;select row Coverage for Injury to Leased Workers EMPLOYMENT Coverage&quot;i] >> internal:label=&quot;select row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02b86dfa-e530-4a58-a0bf-443db47de3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0180fb6e-8203-460e-b28c-c0741358bf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddde2caa-8fb5-4d4b-bbd4-951e23b16de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox</value>
      <webElementGuid>7c1af49a-2adc-4591-8ac3-53c3dd359d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV</value>
      <webElementGuid>ea9de179-0e3b-4fb4-8ed0-92a743576379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>CoveragePatternSearchResultsLV,-</value>
      <webElementGuid>e7f34697-3baa-4b19-8614-ef2aa836e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select row</value>
      <webElementGuid>8a91bc85-29b4-461f-a616-df1bce32e8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>d5fa6f89-3284-4168-b61c-801737ec33d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>aca10c31-71f5-4efc-a0c8-c0248bc6c7ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox']</value>
      <webElementGuid>a2282b17-27f6-4269-b3e7-8546d4166ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox']/input</value>
      <webElementGuid>03cac902-b6a0-4404-a34f-17fd6f7c982c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td/div/div/input</value>
      <webElementGuid>25f004e6-c369-446f-8bd5-c74e3132a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-14-_Checkbox']</value>
      <webElementGuid>d134e748-302e-4e9f-9674-8abd83149691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
