<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Electronic Data Liability_Checkbox</name>
   <tag></tag>
   <elementGuidId>ba4d6370-80e8-493e-8900-752d511f94ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;select row Electronic Data Liability OTHER Coverage&quot;i] >> internal:label=&quot;select row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7c717d1-3878-43e5-97fb-1c9a1f3554b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8e2d46f8-8b2c-46d5-8c49-c607bbd98536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20f04b9a-b454-4cc3-97f2-5d0dba00c172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox</value>
      <webElementGuid>a3b09c5e-b846-40a1-82c0-ad1414939a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV</value>
      <webElementGuid>8ea41ef2-9608-4944-8b9d-a30111339c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>CoveragePatternSearchResultsLV,-</value>
      <webElementGuid>b87d9abd-4d6a-4a11-802f-5049c7244ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select row</value>
      <webElementGuid>7da9314b-3d90-494d-9360-24a20fb66ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4a0a1a7a-77c0-4719-9568-eead6999e43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>42663985-98ca-400d-98d8-98e22aa43402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox']</value>
      <webElementGuid>b2b92f3e-9c5a-4aea-b079-7e23018ecab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox']/input</value>
      <webElementGuid>7d59c1f4-68c6-4a0a-8c88-1f53ed9873dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/div/div/input</value>
      <webElementGuid>3bb25ef2-750e-4d23-9799-544d24d2d443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-7-_Checkbox']</value>
      <webElementGuid>2a576f87-82d5-45d0-82d7-99eceec09a54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
