<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Limited Fungi or Bacteria Coverage_Checkbox</name>
   <tag></tag>
   <elementGuidId>8ba09f7f-ed43-4937-81af-1c225fbc8939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;select row Limited Fungi or Bacteria Coverage OTHER Coverage&quot;i] >> internal:label=&quot;select row&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff5e9ebc-492c-4000-892b-cd83a19d095b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>69295670-22fd-4a29-81d5-ef2626fe7004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>20fec09e-b127-497a-a09e-676b1540356e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox</value>
      <webElementGuid>063b0766-5282-40c7-a5e0-5b5981a91078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-scope</name>
      <type>Main</type>
      <value>CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV</value>
      <webElementGuid>f88751ed-1dca-4121-8205-bd3c0d20d154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-flags-target</name>
      <type>Main</type>
      <value>CoveragePatternSearchResultsLV,-</value>
      <webElementGuid>9ef2121e-4cb5-42cf-bbde-1da54605e66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select row</value>
      <webElementGuid>5dda6981-627b-46e8-8006-dc8c45fc63a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5f420212-3822-4308-8b6e-70d7b5ab7374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox&quot;)/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>baa5a4ec-1263-4351-97fe-295fd5d49845</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox']</value>
      <webElementGuid>a6487b90-8c56-4ac3-9adf-254403cd46d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox']/input</value>
      <webElementGuid>e2c848d8-fc4a-40eb-8c68-b06a37a6d82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td/div/div/input</value>
      <webElementGuid>b498c16b-a131-4c4a-ad35-fb42a4246d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'CoveragePatternSearchPopup-CoveragePatternSearchScreen-CoveragePatternSearchResultsLV-10-_Checkbox']</value>
      <webElementGuid>304810f8-d02c-476c-a487-26405088d517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
