<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Commercial Auto</name>
   <tag></tag>
   <elementGuidId>4aa1e59a-1e15-47ce-92bd-9a1ddeb19b0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5ad19e65-a29c-41b3-92ee-e2f654a723ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission</value>
      <webElementGuid>f4d666da-4def-4fcd-8631-b9ab8e5301d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>4f34eb53-c806-4d97-b245-691ee9d77cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>2963c732-40e5-4640-bf67-eed75f504f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>0115b6eb-2bed-4d0b-bef0-ca8e60e7a280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c50f204-7dd4-4ccb-83a1-27d221f75a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>bec5b090-4b1b-4ff0-8f8a-b9d2839f5a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission&quot;)</value>
      <webElementGuid>ffec7dd9-2f9d-41a9-bd74-a6e267fd8fa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission']</value>
      <webElementGuid>420a61cc-e997-43f8-b209-9d25c5083d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-Select']/div/div/div</value>
      <webElementGuid>92919a17-ee8d-4cb5-988e-8edb04bd4e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[1]/following::div[3]</value>
      <webElementGuid>895b800b-f040-4d3b-afc6-f82583936a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Owners'])[1]/following::div[8]</value>
      <webElementGuid>e0fe8c7b-a1ef-4e77-be34-458580fd4102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Auto'])[1]/preceding::div[1]</value>
      <webElementGuid>1292aaeb-621c-4b1c-b48a-811ff7ad12a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Auto'])[2]/preceding::div[5]</value>
      <webElementGuid>84cc21e9-c321-4117-967f-922f0d774469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/div</value>
      <webElementGuid>da803267-c24b-45f7-9a27-34e8f1ff90d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-1-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>b58911f3-0e8a-4fa7-8338-d13054075250</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
