<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GeneralLiability_Select</name>
   <tag></tag>
   <elementGuidId>81cf1713-003f-45eb-bc88-edc4beb8bd71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>84c8666a-eef6-4e93-ad3a-d2eb14b17ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission</value>
      <webElementGuid>b2a2fbda-9bd7-400f-acd3-57b6d8282535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--LinkCellWidget gw-mini-button gw-actionable gw-focus</value>
      <webElementGuid>097515fe-6f35-42e3-8e8c-9d046561e105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>4576b609-3669-4c69-9a95-d47baaa03e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7c7f77c8-1515-480c-8171-7954c7ea8bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9c9d9b03-4086-4836-804c-6b4908ea35a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>03304b11-d9e7-44aa-aa22-b6281e7f3597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission&quot;)</value>
      <webElementGuid>eba94972-57e7-416c-b444-3ab0dc18e5fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission']</value>
      <webElementGuid>de53aa3f-9fc1-43d1-a4dd-828ae140d123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-Select']/div/div/div</value>
      <webElementGuid>0793ebbe-615c-4d69-a835-aa11ae4fd571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available'])[4]/following::div[3]</value>
      <webElementGuid>f01d0de4-2bb3-4a08-b7bc-faafb8e967c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Property'])[2]/following::div[8]</value>
      <webElementGuid>dff63a4b-b3e4-428c-8c5d-440495432279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Liability'])[1]/preceding::div[1]</value>
      <webElementGuid>e199a724-2d32-44eb-8ae5-9717bce60025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Liability'])[2]/preceding::div[5]</value>
      <webElementGuid>7c924560-1f9a-49c6-a633-5a873dc21804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/div/div/div</value>
      <webElementGuid>7d80a855-6935-4221-a605-28a69cf185dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewSubmission-NewSubmissionScreen-ProductOffersDV-ProductSelectionLV-4-addSubmission' and (text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>3ca7afaf-8e16-44bc-939a-2b30fa953521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
