<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Default Effective Date</name>
   <tag></tag>
   <elementGuidId>4febf70f-e433-4ee3-8623-0beb3edea364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MM/dd/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aca39ec1-e307-4984-8fd7-72da061e2e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09855040-b29a-4231-9bbc-7c9ffc6e25b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-min-visible gw-DateValueWidget--dateInput gw-focus</value>
      <webElementGuid>f85d83cc-b7bb-4c55-b003-9d02b8cd254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate</value>
      <webElementGuid>039987c2-1fa8-4975-8d8b-6fedb113f34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d473c1ba-a0cf-44c2-bd5b-76e56fd07379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>07/02/2025</value>
      <webElementGuid>f0081666-1048-46d5-82c9-a2337e8da47c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/dd/yyyy</value>
      <webElementGuid>b8b1fede-dc56-4ae8-9f23-9085556812aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>date input</value>
      <webElementGuid>116da940-c5a0-4d9b-9fa2-b04d5311bda8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-focus</name>
      <type>Main</type>
      <value>gwDateValue.showDatePickerOnFocus</value>
      <webElementGuid>c3b32761-249f-4894-9c6b-98dc9ee720b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>cfb5ddbe-930f-40c3-adb2-200df13311db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>a0ed2b6f-ca6e-44ad-b6e7-e8512a049f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>817390a0-39a5-4cfd-afa0-b453555a0d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-min-visible gw-DateValueWidget--dateInput gw-focus&quot;]</value>
      <webElementGuid>451af7e3-7747-476f-b84e-3393f14ce59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate']</value>
      <webElementGuid>44dabf9d-750d-4513-b377-215707186d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate']/div/input</value>
      <webElementGuid>5911ba7d-3670-4e97-b624-39e80a6b0e18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/input</value>
      <webElementGuid>19232303-8173-4b82-8d65-16b6821a26d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultPPEffDate' and @placeholder = 'MM/dd/yyyy']</value>
      <webElementGuid>8f3bb443-0ae7-4046-8b97-2594ee96638f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
