<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_state</name>
   <tag></tag>
   <elementGuidId>11c44b08-1ef7-4fc3-b42e-b51d1082886e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3fb01fb-9c42-4919-a400-ec919f736323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState</value>
      <webElementGuid>9b0f9489-04f8-4196-bea7-3aefe3229f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4229a9db-cc48-4e50-8762-455d621499ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>1f21cbdb-faf4-422b-8dce-d668ca21b9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   A.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaFranceGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaJ.B.T.JapanKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUnited KingdomUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   </value>
      <webElementGuid>453bdace-e1f0-4ae1-a3d3-c737d4b90d37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>71539239-37a4-4438-aad2-6c45a28987ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState']</value>
      <webElementGuid>cdc75d34-911a-48bb-bf49-83bb7dae2fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState']/div/div/select</value>
      <webElementGuid>398f45b2-dd01-44b8-96eb-33baea41646f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Base State'])[1]/following::select[1]</value>
      <webElementGuid>454c6d30-f981-49b1-8449-ff350bf5a0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Type'])[1]/following::select[2]</value>
      <webElementGuid>47886d5f-07b9-4bb7-b6e3-1f6a36be5166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Effective Date'])[1]/preceding::select[1]</value>
      <webElementGuid>07138241-b14a-42e0-b3bd-3189c37e55d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/preceding::select[1]</value>
      <webElementGuid>0d3d7afa-8db5-44b7-a456-7147b8177b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/select</value>
      <webElementGuid>23f4adab-2dae-4025-83d3-c1ab1a127ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'NewSubmission-NewSubmissionScreen-ProductSettingsDV-DefaultBaseState' and (text() = '   A.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaFranceGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaJ.B.T.JapanKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUnited KingdomUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   ' or . = '   A.C.T.AlabamaAlaskaAlbertaArizonaArkansasBaden-WuerttembergBavariaBerlinBrandenburgBremenBritish ColumbiaCaliforniaColoradoConnecticutDelawareDistrict of ColumbiaFederated States of MicronesiaFloridaFranceGeorgiaGuamHamburgHawaiiHesseIdahoIllinoisIndianaIowaJ.B.T.JapanKansasKentuckyLouisianaLower SaxonyMaineManitobaMarshall IslandsMarylandMassachusettsMecklenburg-VorpommernMichiganMinnesotaMississippiMissouriMontanaNebraskaNevadaNew BrunswickNew HampshireNew JerseyNew MexicoNew South WalesNew YorkNewfoundland and LabradorNorth CarolinaNorth DakotaNorth Rhine-WestphaliaNorthern Mariana IslandsNorthern TerritoryNorthwest TerritoriesNova ScotiaNunavutOhioOklahomaOntarioOregonPennsylvaniaPrince Edward IslandPuerto RicoQuebecQueenslandRhineland-PalatinateRhode IslandSaarlandSaskatchewanSaxonySaxony-AnhaltSchleswig-HolsteinSouth AustraliaSouth CarolinaSouth DakotaTasmaniaTennesseeTexasThuringiaUnited KingdomUtahVermontVictoriaVirgin IslandsVirginiaWashingtonWest VirginiaWestern AustraliaWisconsinWyomingYukon   ')]</value>
      <webElementGuid>1273ab2a-fcb6-40c0-97d8-0b0652d16034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
