<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>fe26e158-b5ca-4fcc-8d44-969624df8431</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1256834b-97ae-40b0-b75a-2c66c0f21337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search</value>
      <webElementGuid>25223ff7-c868-40a9-b100-43cebb21badc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--InputWidget gw-big-button gw-actionable gw-focus</value>
      <webElementGuid>66b3acba-be66-4be7-8997-8dc5a9d094e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>2f1731dd-c8a3-49ce-89ea-9f504d34510e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-shortcut</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;,&quot;key&quot;:&quot;S&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;S&quot;}</value>
      <webElementGuid>6fc3318c-f7ee-4d51-8d23-b191aa980cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-default</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;,&quot;key&quot;:&quot;ENTER&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;S&quot;}</value>
      <webElementGuid>cc919b66-0297-4e67-acbd-227be02df703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>71633697-096e-4057-a49a-4455fb8d20f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f05f4e7-dbbb-4db0-9179-87e9204ac095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>32bd7a29-3828-4b5a-bd2a-991a793ba808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;)</value>
      <webElementGuid>6db0667c-bcc8-4daf-8c56-6e24940031a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search']</value>
      <webElementGuid>e0e0e0bc-9299-47f2-8bea-74c4ca503e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-searchBtns']/div[2]/div/div</value>
      <webElementGuid>68426240-63eb-4afa-b8d4-8c599e191028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Type'])[1]/following::div[11]</value>
      <webElementGuid>6304ed0a-b2d2-48aa-87a1-67fa52862aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[2]/following::div[18]</value>
      <webElementGuid>16e7f028-c3ee-4877-a098-9190a93b0fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='earch']/parent::*</value>
      <webElementGuid>b7503ad6-9851-4a1d-9094-9feda13207c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>bc7d197f-4c14-4e66-a9b9-b4450ca64e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-SearchAndResetInputSet-SearchLinksInputSet-Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>aca10600-d70b-420d-b0df-c151dacff3e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
