<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keywords</name>
   <tag></tag>
   <elementGuidId>6948fab3-0681-45a1-926a-9cd112e35e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f5ab3a6-5eab-467d-97e3-91759b506bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8c8c2987-68e2-4e22-b12b-c243289c4098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords</value>
      <webElementGuid>f1b76c83-d110-4daf-ada0-bfa036671f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack gw-focus</value>
      <webElementGuid>aaa54cfd-839b-4e5d-8639-cf9cc5d9219a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1aa801ca-63e6-4434-bcd2-2bdd62f1de46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5679370f-b222-4bde-b73a-2a7ee3203fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2b60ab51-90e9-4462-ae89-f93512b76a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>e1b34796-2e83-4779-a048-093f7787eefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>0511f87c-6a44-4165-b593-56c68e20875b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords']</value>
      <webElementGuid>5a827309-1abf-4ab3-bd59-9059bd1d91f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords']/div/input</value>
      <webElementGuid>a4ad571b-419f-44a1-bfc7-c7bba11077c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>7ca209cb-3fe9-43c1-857b-302cb4c06f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-Keywords']</value>
      <webElementGuid>cb8631d2-592e-4f35-b074-261b3c0be85e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
