<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_BatchInteractiveOn-Demand</name>
   <tag></tag>
   <elementGuidId>d9049f04-e24d-4b74-9e9e-6d569c9b30d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23cb06f6-c927-405a-bde3-7a60277831aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType</value>
      <webElementGuid>86dcd9ac-5880-4816-b357-4fbc371a5816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90742676-2987-4bc4-aaed-a37979dbddf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack gw-focus</value>
      <webElementGuid>259ae742-24fa-49bb-9830-262127bff31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   BatchInteractiveOn-Demand   </value>
      <webElementGuid>6fbd4c43-aa46-43e7-8331-88a0b0b10e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>df2fd3b5-ad73-4845-b3eb-e6aaa3d807e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType']</value>
      <webElementGuid>ea05ff86-13ce-43f0-aa20-974a41001102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType']/div/div/select</value>
      <webElementGuid>41b49930-11bb-414a-b6a8-94dad3061a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creation Type'])[1]/following::select[1]</value>
      <webElementGuid>4ff10a78-6442-456f-8c7b-c85f98cc8aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effective Date'])[2]/following::select[1]</value>
      <webElementGuid>f571c563-2e68-4845-a73b-ddd5cf70dde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/preceding::select[1]</value>
      <webElementGuid>d1487b86-e5b9-47f9-b230-4445a77d5a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/select</value>
      <webElementGuid>e9244472-d48b-4cbf-8242-01b7dc68b6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentCreationType' and (text() = '   BatchInteractiveOn-Demand   ' or . = '   BatchInteractiveOn-Demand   ')]</value>
      <webElementGuid>e8fc1731-adaa-4f16-b2c2-5c6c53035303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
