<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Delivery Channel</name>
   <tag></tag>
   <elementGuidId>75dab353-4e53-478e-b7ba-38a6deb7f708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>15879b5f-dafd-4650-8a53-a14a4965b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel</value>
      <webElementGuid>0d2ae0da-cc46-4387-b651-412f556c4ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fcf5cb3e-4aa0-469f-b9f5-d3d7722ff361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>8281dd06-d72f-4221-a005-6843ca5bd9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>EmailFaxPrintSMS   </value>
      <webElementGuid>7e154ab5-8de1-442e-b1f1-f6ce841ceadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>9a3c8d23-b580-4c71-96c7-6960d2fbad91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel']</value>
      <webElementGuid>9b03cd5a-dfc2-462a-87f7-d068c4fce931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel']/div/div/select</value>
      <webElementGuid>35232c65-add1-4bb2-b63b-4df08cdd1a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::select[1]</value>
      <webElementGuid>cdb12a3e-c94d-4c2c-978b-f4c071112604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::select[1]</value>
      <webElementGuid>12ffd142-b360-4a0d-971c-3493031e6b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kuiydfgcvj'])[7]/preceding::select[1]</value>
      <webElementGuid>f44f95fd-8811-4c5a-bc63-93aaad973ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::select[1]</value>
      <webElementGuid>eeb7b2a5-815e-44b3-b882-8680be593738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>eb0cb4d9-fe1f-420d-ac58-dc6ce226d55c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-AddRecipientsPanel-AddRecipients_AccPanelSet-PrimaryRecipientDeliveryChannel' and (text() = '   &lt;none>EmailFaxPrintSMS   ' or . = '   &lt;none>EmailFaxPrintSMS   ')]</value>
      <webElementGuid>6e0dd157-52af-4295-9b17-62ea87c9197b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
