<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Document Type</name>
   <tag></tag>
   <elementGuidId>26081025-0f09-4a27-9fb4-49c5a49a0598</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3cb6a417-05a7-4164-af1e-a9773c6610eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType</value>
      <webElementGuid>8d882854-7880-4bd3-b603-d533d8500b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>62694f66-7a9d-467e-8655-e064e3401a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-noTrack gw-focus</value>
      <webElementGuid>8b7ff158-7dd6-4527-824e-15d8435741ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Audit reportBinderConfirmation letterCredit reportDeclination letterDecSheetDiagramEmailEmail SentInspection reportLetter receivedLetter sentLoss historyLoss informationMVRNew business applicationNot-Taken letterOtherPolicy summaryQuoteRenewal information/instructionsStatement   </value>
      <webElementGuid>3ee2bef2-3cc3-40e5-80fb-24ebd45873a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-noTrack gw-focus&quot;]</value>
      <webElementGuid>5802b902-7fad-4b1c-bd0c-a7e24fa29112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType']</value>
      <webElementGuid>47cd7fa3-2406-4391-b792-ac53af6bb4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType']/div/div/select</value>
      <webElementGuid>dae2c1af-2a74-4eb4-af9e-12559c102a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Type'])[1]/following::select[1]</value>
      <webElementGuid>418bc916-4839-4878-b63c-f63f85d74343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Template'])[1]/following::select[1]</value>
      <webElementGuid>42668dd5-9440-44a8-b30b-5dd4422e41f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[2]/preceding::select[1]</value>
      <webElementGuid>0c56ef6f-4db2-42ec-901c-96400e82e0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords'])[1]/preceding::select[2]</value>
      <webElementGuid>e30bd50b-e2bb-487c-8a0f-0484ce72c2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c0d134ce-aa45-4a9e-892d-eb1dcdd5b1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'NewDocument_AccWorksheet-NewDocument_AccScreen-NewDocCardsCV-DocumentTemplateSearch_AccPanelSet-DocumentTemplateSearch_AccDV-DocumentType' and (text() = '   &lt;none>Audit reportBinderConfirmation letterCredit reportDeclination letterDecSheetDiagramEmailEmail SentInspection reportLetter receivedLetter sentLoss historyLoss informationMVRNew business applicationNot-Taken letterOtherPolicy summaryQuoteRenewal information/instructionsStatement   ' or . = '   &lt;none>Audit reportBinderConfirmation letterCredit reportDeclination letterDecSheetDiagramEmailEmail SentInspection reportLetter receivedLetter sentLoss historyLoss informationMVRNew business applicationNot-Taken letterOtherPolicy summaryQuoteRenewal information/instructionsStatement   ')]</value>
      <webElementGuid>15cf5429-5385-4a23-8126-fab6c1f9fb44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
