<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Qualification</name>
   <tag></tag>
   <elementGuidId>828c7c9a-ed6e-4328-8efb-b69715a6f527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SubmissionWizard-SubmissionWizard_PreQualificationScreen-ttlBar']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-TitleBar--title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Qualification&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>748dea1d-6278-40a7-8ee7-1b714435186d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-TitleBar--title</value>
      <webElementGuid>2067b2c4-4176-4b00-b9c2-be5bd1019b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>2d231741-ce54-46e4-af8c-38fa75059783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e7afe080-ad58-43de-a748-eebf0dd11c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Qualification</value>
      <webElementGuid>92e2081d-9fe7-4ddd-ada0-1dabbd1d52e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-SubmissionWizard_PreQualificationScreen-ttlBar&quot;)/div[@class=&quot;gw-TitleBar--titles--container&quot;]/div[@class=&quot;gw-TitleBar--title&quot;]</value>
      <webElementGuid>55ac9d48-5c94-45b6-b572-2d3a8b689e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-SubmissionWizard_PreQualificationScreen-ttlBar']/div/div</value>
      <webElementGuid>03984f7c-bc95-4f33-b4a9-6fb98809d6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steve Smith'])[1]/following::div[5]</value>
      <webElementGuid>3069b040-a70b-40b7-ba9c-422a638354af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwriter:'])[1]/following::div[6]</value>
      <webElementGuid>676f2937-594e-43fe-aad7-7aa9df26e60e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ba'])[1]/preceding::div[3]</value>
      <webElementGuid>03103215-02bd-4048-9215-aa887305cc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[5]</value>
      <webElementGuid>e287c595-d654-462a-abcf-7fc8187b1aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[4]/div/div/div</value>
      <webElementGuid>37b1dd8d-637a-406f-be60-ba440724891e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Qualification' or . = 'Qualification')]</value>
      <webElementGuid>523c0cc2-3ce4-403a-beeb-ac2aadc24735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
