<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coverages</name>
   <tag></tag>
   <elementGuidId>3f2edef0-cbc3-4bdc-a820-09e48422f40c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CPBuildingPopup-BuildingCoveragesTab']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus > div.gw-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Coverages&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d335e50-49a0-4111-930c-5dcbc026753b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>c89dd2ac-cee7-4a0e-bbd7-f3dee6dda5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Coverages</value>
      <webElementGuid>5402563a-44d6-4965-9902-280be91168f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coverages</value>
      <webElementGuid>ffc71e93-b26b-4a2e-9144-797a7cd3864f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-BuildingCoveragesTab&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>6c531557-666f-4cd0-a5d9-d69393845438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-BuildingCoveragesTab']/div/div[2]</value>
      <webElementGuid>4a253af4-42ff-4e08-ae61-b70213b24355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Co'])[3]/following::div[1]</value>
      <webElementGuid>de62330b-d3b8-4505-897c-308fa0174a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::div[5]</value>
      <webElementGuid>0c465afe-2967-4078-9033-b52677332133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AI'])[1]/preceding::div[1]</value>
      <webElementGuid>90ea6f6a-128c-4513-af3b-560e3a83bc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Interest'])[1]/preceding::div[3]</value>
      <webElementGuid>17d193db-6a81-437f-98fd-5c35a7261b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Coverages']/parent::*</value>
      <webElementGuid>73f12d4b-87e1-449e-bcd5-f7b859736d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div[4]/div/div[2]/div/div[2]</value>
      <webElementGuid>dba35fed-b5bb-468b-8119-4828630511ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Coverages' or . = 'Coverages')]</value>
      <webElementGuid>b2ca2721-2f46-4068-a5b2-343c04f609ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
