<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Extra Expense Coverage_checkbox</name>
   <tag></tag>
   <elementGuidId>8fd5b5b2-438f-40fc-9ca1-ad9df64de2e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Extra Expense Coverage visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa2c59b4-8ea8-4c22-9f35-7e046bd26c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>20ef65f8-25ad-4cb4-80c9-19f6170bd44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8d625f73-97a7-4d11-96bb-81e5127f037c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Extra Expense Coverage visibility toggle</value>
      <webElementGuid>097cc61d-ac74-453c-a21a-df8bb667206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>6c7a6e86-feb3-4633-87b9-0a663cf08f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>b7937808-05ce-4170-b4f4-37c57796505d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>592901fe-dedb-47dc-b60e-ce8cdb5f25d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>bf6c8c35-0f42-4685-8a12-cfbe04ba47b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>1dfaae35-13f9-4e4a-893f-93d11f3b7bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CPBuildingPopup-CPBldgSuggestedCovDV-IncomeAndExpenseIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>7ac8d88e-73b1-4fc5-bae1-d45516576cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
