<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Coverage_checkbox</name>
   <tag></tag>
   <elementGuidId>ae4b1453-bc1c-4fec-a38c-509f2fea4089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Building Coverage visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f73824cd-2fed-4122-8881-fd5a6b54f9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>f4bdb74c-cbd9-4d4b-bd15-c836e66c9069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f6f6551f-c923-4aca-8d7f-af6b823a4369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Building Coverage visibility toggle</value>
      <webElementGuid>2f9777cb-cb32-4a70-95e3-8c98427b447e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>02036cfe-0ca9-4899-b1e9-b73001007cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>c97563a4-7021-4d0b-a435-d890b5c4b32e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>bbc816e7-2fd3-4b6a-97c8-e2a94eb1d108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>bfd7d40e-d66c-4ce9-a2bf-e2c3e32eb0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>33750c3b-f0fd-46a9-a434-a28c96bdb2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-0-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>e3d0686d-cf11-41d4-a1b1-66a7a015d7d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
