<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business Personal Property Coverage_checkbox</name>
   <tag></tag>
   <elementGuidId>155479d6-0b15-4539-bc6f-73808e2ed263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Business Personal Property Coverage visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdf6e0ca-a695-4aa8-91e6-7edc92da3dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>cc8ca88e-4048-45fb-82a7-c1e052f7311c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7116ccda-4c6d-43e5-bfdd-2d7bda534dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Business Personal Property Coverage visibility toggle</value>
      <webElementGuid>e08c270e-282f-4f66-8a35-5f0e47858454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>1c8fecc9-7825-4fc7-ad86-2210ff2f9d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>4157a6e3-f576-463a-8276-1e095016e454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>5014a72d-6d29-484e-95ae-79931cc71e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>1a22ba08-8ac1-47c6-88d7-cb5ec483fd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>54373ee9-81ab-4c25-b2e6-7ca27fe7510b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'CPBuildingPopup-CPBldgSuggestedCovDV-bldgAndPropIterator-1-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>61e39b9c-ff7c-4734-a77b-a0d2436a1b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
