<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Property Class Code</name>
   <tag></tag>
   <elementGuidId>4ca4cfc3-4a8d-4284-aad7-3e381bfddf4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='CPBuildingPopup-DetailsDV-ClassCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f9d0be9-1e99-440b-9bf9-4505cb512e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0fbb5922-be8e-4fdc-83e9-d306be3f1b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-DetailsDV-ClassCode</value>
      <webElementGuid>4811a7ec-1f96-43bd-a1d6-a420b4ba165a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-picker-input gw-focus</value>
      <webElementGuid>2b393acf-7e6f-4fb1-aaec-04f4c49ce280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b2128b6-448f-4f40-8a61-b5f3bc075406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50000</value>
      <webElementGuid>c129312c-cae2-45b9-9919-fdf7ebf9c94a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7c9ce6dc-8979-43d4-8491-95632222027f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>a3ca068b-0e55-453d-88c8-6d61dc8cdd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-DetailsDV-ClassCode&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-picker-input gw-focus&quot;]</value>
      <webElementGuid>b292f9cb-c45e-451c-999f-fcfcc5462843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='CPBuildingPopup-DetailsDV-ClassCode']</value>
      <webElementGuid>6cbd3e96-102d-4742-aeaa-043eefd9c915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-DetailsDV-ClassCode']/div/input</value>
      <webElementGuid>4ffbc1a5-bfc5-449c-b885-76ed45ae12a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>3206a66a-90e7-44f0-adb3-d8f86d864f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CPBuildingPopup-DetailsDV-ClassCode']</value>
      <webElementGuid>0deea949-f395-46ec-90a9-354b730af43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
