<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Coverage From</name>
   <tag></tag>
   <elementGuidId>9bb4fd93-44da-4abc-acd7-0146b373e19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='CPBuildingPopup-DetailsDV-CoverageForm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1569ce1d-8a95-49db-bfb9-63bf0eadd771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CPBuildingPopup-DetailsDV-CoverageForm</value>
      <webElementGuid>84bc75be-a6a3-445f-bc06-10501d25ef0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fc095178-c97a-4bd6-8df5-20208a21d038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>45c2b33c-ef82-4d86-8149-bf9feb5e56ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   </value>
      <webElementGuid>b4409c86-5ac2-4d05-ad84-79a25b8e63c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPBuildingPopup-DetailsDV-CoverageForm&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cbc77b8d-33dd-4da9-b1bd-fa8ec3a6d40b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='CPBuildingPopup-DetailsDV-CoverageForm']</value>
      <webElementGuid>e0299216-6e80-4ace-aede-0574cb41b7a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPBuildingPopup-DetailsDV-CoverageForm']/div/div/select</value>
      <webElementGuid>209efc73-8fc2-4258-89b9-bfdfa4b50dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Form'])[1]/following::select[1]</value>
      <webElementGuid>5345ff89-3acc-4963-bc44-fd9a8f0403a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding and Lodging Houses, Rooming Houses, Fraternities and Sororities - Up to 10 Units'])[1]/following::select[1]</value>
      <webElementGuid>f0407c49-38f4-487a-a67d-44bdc6fb9c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[1]/preceding::select[1]</value>
      <webElementGuid>b786b045-c2ea-460d-a2d6-3148ca30a8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Type'])[1]/preceding::select[1]</value>
      <webElementGuid>78163719-1a05-4e58-87d6-55512cac40ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b71cd0a2-d6a5-4809-8039-91c3e3004251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'CPBuildingPopup-DetailsDV-CoverageForm' and (text() = '   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   ' or . = '   &lt;none>Building and Personal PropertyCondominium AssociationCondominium Unit-Owners   ')]</value>
      <webElementGuid>73cfa787-50b2-484b-98ff-d98b4a14290b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
