<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Today</name>
   <tag></tag>
   <elementGuidId>eb0ab6b5-e368-4e2d-8dd5-45b944899ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gw-datePicker']/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-datePicker--today.gw-button-secondary.gw-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Today&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cc01e824-3ebd-4f7a-8e24-fba0a74776ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-datePicker--today gw-button-secondary gw-focus</value>
      <webElementGuid>9ae3403e-9135-4d2c-baa4-f38ed3837998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>75bcdbd0-3330-4737-93fd-5af0ad9c1836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e6261631-9362-4045-ab30-7a9eccc72478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>gwDatePicker.today</value>
      <webElementGuid>5447824a-6ad0-4068-9168-c07ab59ed5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>c4017960-f27a-4b1b-a7b8-0af934cd3639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gw-datePicker&quot;)/div[@class=&quot;gw-datePicker--footer gw-inDatePicker&quot;]/div[@class=&quot;gw-datePicker--today gw-button-secondary gw-focus&quot;]</value>
      <webElementGuid>dfd681d5-0ebb-41f2-b019-7b7ccb41585e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gw-datePicker']/div[2]/div</value>
      <webElementGuid>c9b3d312-dd7b-49a9-a730-7a1c9d5dd39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[3]/following::div[86]</value>
      <webElementGuid>d582bc15-9bb2-4a3a-91a4-67b91e97b638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F'])[1]/following::div[87]</value>
      <webElementGuid>7d907407-1180-42b4-a0bf-34d1b4455081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected Day'])[1]/preceding::div[2]</value>
      <webElementGuid>9286b4f3-cc2d-4f2e-8ce6-9f04e7c340c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimated Premium'])[1]/preceding::div[6]</value>
      <webElementGuid>a446d1d3-f8c1-4136-9e39-b2119e8ab653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>4527ec20-57ba-4868-8443-0ca74b7c8bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/div/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>6bc34505-fb85-4b85-a98a-c1660fd31af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>68163402-9e5e-4091-bb1e-b6ac5d71b921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
