<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Finalize Document_thunderheadDraftEditorWindow</name>
   <tag></tag>
   <elementGuidId>e5fa3e11-9ad5-4d99-8c44-71a2af1705ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='thunderheadDraftEditorWindow']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#thunderheadDraftEditorWindow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;thunderheadDraftEditorWindow&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ab1782c8-9931-406a-901c-a577db16c2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>thunderheadDraftEditorWindow</value>
      <webElementGuid>e6e2d1f6-5886-46dc-9820-dcc28375ba96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thunderheadDraftEditorWindow</value>
      <webElementGuid>d74409f7-55de-4c5a-aa17-6c8a2447e3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb298f01-7cd3-4781-9717-73d1a788bb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>859c177e-2d02-469c-9b51-a00f5b64142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0686124b-70ba-4ae9-a3fa-27f681e0cf77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://na10-sb.smartcommunications.cloud/one/draft-editor/draft-editor.jsp?clientServer=http%3A%2F%2F52.14.128.106%3A443</value>
      <webElementGuid>8ea1d9c7-64c9-43a4-bbe7-4e71f1fbb7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thunderheadDraftEditorWindow&quot;)</value>
      <webElementGuid>e897a3d4-d7ca-4151-b1bf-266a331cacaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='thunderheadDraftEditorWindow']</value>
      <webElementGuid>ffa3d0b9-6f39-4867-8855-e90e6860cdef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='smartcommApplication']/iframe</value>
      <webElementGuid>915c6b4c-3934-4279-abfa-61d1e59d447b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/iframe</value>
      <webElementGuid>dd0829a6-0932-4d13-9d38-42d06cdec1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'thunderheadDraftEditorWindow' and @id = 'thunderheadDraftEditorWindow' and @src = 'https://na10-sb.smartcommunications.cloud/one/draft-editor/draft-editor.jsp?clientServer=http%3A%2F%2F52.14.128.106%3A443']</value>
      <webElementGuid>5d0bda8b-9d45-439b-a7dc-b843440338a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
