<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox_Hired Auto Specified Causes of Loss</name>
   <tag></tag>
   <elementGuidId>3fbbcafc-bafa-4556-a892-49c9bf9fe9a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Hired Auto Specified Causes of Loss visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4b3d9bd-0dea-44b5-9886-f2f24417dd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>16d8b2f2-8bd0-4102-9d21-c51d34dc5514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e0a8fc8f-81de-49d3-9b9e-d6b181512c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Hired Auto Specified Causes of Loss visibility toggle</value>
      <webElementGuid>471eb080-1b45-4dc3-841f-13e4661ef6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>5ed84bb6-d2ab-453d-89d9-4898b146e823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>e845985a-08a1-45dd-aa01-251346d7201c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>d9fa560e-a591-4df7-82e4-53ff234eb88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>7fa6b069-1d0a-468e-a96d-23df4791f0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/input</value>
      <webElementGuid>4edcee80-323a-4201-97fb-b5b371f8addd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BAPHiredGrpIterator-3-BAHiredGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>89507c3a-50e3-4af7-9f37-13f727262b03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
