<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bobtail Liability</name>
   <tag></tag>
   <elementGuidId>532cb438-e339-4f51-bcac-42ed595fc83a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Bobtail Liability visibility toggle&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3d59006-1210-4052-b249-f354589ded86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox</value>
      <webElementGuid>f03c9406-0319-4fc6-bad0-ab5583845e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e4291a13-f8b2-47ed-9b8e-1d4d714fb9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Bobtail Liability visibility toggle</value>
      <webElementGuid>1ddc383e-e9d9-4720-8748-755a87a39458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>dbdf37e9-c497-4758-9499-8f19b40f7338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>cb1cdafa-ca23-4954-a275-7a152ae8c75e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']</value>
      <webElementGuid>7701c1ca-3428-4676-b152-9d7b5d1b9fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox']/div/input</value>
      <webElementGuid>2996331a-124a-4fd1-b765-20f2ed024070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>f0b56462-fabd-43be-9bbb-757ab00c47d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-1-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-_checkbox' and @type = 'checkbox']</value>
      <webElementGuid>3e5cb72e-6b92-407b-9cb8-129374d3d871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
