<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Coverage Date</name>
   <tag></tag>
   <elementGuidId>20b0e4ca-4c9b-433a-9984-f4f6357f7634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Start Coverage&quot;i >> internal:attr=[placeholder=&quot;MM/dd/yyyy&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c813db35-edff-42c5-946a-965f3cf7ccb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a121816e-ac26-4386-b87f-d7e5a2f0a63d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-min-visible gw-DateValueWidget--dateInput gw-focus</value>
      <webElementGuid>1617a85b-dc14-4d73-8c99-93fe809fbb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput</value>
      <webElementGuid>c6c54d52-7f1f-43b1-b7fa-609e858df37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b7757116-a042-4b58-b974-37ab81a89669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/dd/yyyy</value>
      <webElementGuid>009e830d-e697-464b-8bcc-e99c75db0e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>date input</value>
      <webElementGuid>6cfc0105-101d-4f92-a055-de3741a658e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-focus</name>
      <type>Main</type>
      <value>gwDateValue.showDatePickerOnFocus</value>
      <webElementGuid>9a336116-a720-4ff1-a5db-feac48f86b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a575c5d1-122f-4136-b300-f1c5264fca2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>GW_OFF</value>
      <webElementGuid>f75dc20b-fe11-47ea-b8b2-158aa1e929c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0bd5990b-3ada-4b0b-9038-f444ca66253c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/input[@class=&quot;gw-min-visible gw-DateValueWidget--dateInput gw-focus&quot;]</value>
      <webElementGuid>b67186f8-f10b-4ccb-9b5a-c3d03ff7e8a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput']</value>
      <webElementGuid>d1d34ef3-7ae1-459e-9f51-026c721dbba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput']/div/input</value>
      <webElementGuid>04383474-dd6b-495f-9662-780a0b39eab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>3c8048d1-2149-4419-ad4d-afdb1b0b6fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-1-CovTermInputSet-DateTimeTermInput' and @placeholder = 'MM/dd/yyyy']</value>
      <webElementGuid>7aca04c4-8794-4a9d-b44b-634fd46b8f4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
