<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Liability Limit</name>
   <tag></tag>
   <elementGuidId>6bf75f4c-50b1-4eea-9c05-e984d24887fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d685ba7-d7fb-4f3d-ba8b-851916278980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput</value>
      <webElementGuid>89c46b36-981e-4a24-92c1-054f86e4069a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61922c2e-335f-47b8-a028-768e10d46731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>4d1f8cf8-aa98-4a49-96e7-ff75f1b0ce67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   250/500/100500/750/500100K CSL250K CSL500K CSL1M CSL20/40/15   </value>
      <webElementGuid>386b51ce-1cf6-4067-be29-7adc86654cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>2538eadc-e11c-4498-a049-3b050a4a8fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput']</value>
      <webElementGuid>72559b0b-c0ed-4180-88a6-bc54ff3a9be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput']/div/div/select</value>
      <webElementGuid>e749e64a-b67a-42fa-83e2-1dcc73bfd004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability Limit'])[1]/following::select[1]</value>
      <webElementGuid>1a785aab-42d1-48b4-bc82-f3d9b700b8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability'])[2]/following::select[1]</value>
      <webElementGuid>37e308b1-8c1a-4121-a5c8-622a13b0e716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Payments'])[1]/preceding::select[1]</value>
      <webElementGuid>1285ab97-775f-4234-a1e0-719803064f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Payments'])[2]/preceding::select[1]</value>
      <webElementGuid>9a160555-5b41-48d3-99e4-777d8306beb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/select</value>
      <webElementGuid>ef6964f2-0630-4573-9fc2-1add449f0c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-baLineLiabCatIterator-0-BALiabGroupInputSet-CoverageInputSet-CovPatternInputGroup-0-CovTermInputSet-PackageTermInput' and (text() = '   250/500/100500/750/500100K CSL250K CSL500K CSL1M CSL20/40/15   ' or . = '   250/500/100500/750/500100K CSL250K CSL500K CSL1M CSL20/40/15   ')]</value>
      <webElementGuid>23e11078-b1b9-47a2-ae89-0e9dd3dc00bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
