<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_product</name>
   <tag></tag>
   <elementGuidId>7404d138-94d6-4d68-9d68-9b81429be284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>96e84409-5849-4b06-9c8b-9871461ccea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType</value>
      <webElementGuid>4c8afb61-cffb-4ccd-80d6-50160f609d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6df526a-979c-4048-8cb3-b85b8d393df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-focus</value>
      <webElementGuid>2bb8fbab-f442-4d46-ad55-73d749c80244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>   &lt;none>Business AutoGaragekeepersMotor Carrier and TruckersBusiness Auto Physical Damage   </value>
      <webElementGuid>36d72c76-6be5-41bf-a7fc-e29eb5caf38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType&quot;)/div[@class=&quot;gw-vw--value&quot;]/div[@class=&quot;gw-select-wrapper&quot;]/select[@class=&quot;gw-focus&quot;]</value>
      <webElementGuid>662f886a-a495-4ea1-998a-02e5b9826667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType']</value>
      <webElementGuid>8d1a8fe5-52e4-4dd2-b0d5-a7c767cd0f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType']/div/div/select</value>
      <webElementGuid>960f9705-012e-47ea-8966-44d83df36d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::select[1]</value>
      <webElementGuid>55d63350-3b13-4817-8443-4c618c7f6930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Insureds'])[1]/following::select[1]</value>
      <webElementGuid>c3f6de2e-97c6-4115-8edb-8cb8de34e2ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fleet'])[1]/preceding::select[1]</value>
      <webElementGuid>498d1cdf-993c-49c7-963f-cd1950d50d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Commercial Auto Owned Liability Group'])[1]/preceding::select[2]</value>
      <webElementGuid>f26e5618-f179-4106-ae1e-98660cba73d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b492eaf0-7fd8-4ae4-b59f-9851be2c507f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'SubmissionWizard-LOBWizardStepGroup-LineWizardStepSet-BALineScreen-BALinePanelSet-BALineCoveragePanelSet-BALineDV-PolicyType' and (text() = '   &lt;none>Business AutoGaragekeepersMotor Carrier and TruckersBusiness Auto Physical Damage   ' or . = '   &lt;none>Business AutoGaragekeepersMotor Carrier and TruckersBusiness Auto Physical Damage   ')]</value>
      <webElementGuid>792e26f6-ef70-4ba6-bc39-fd7f02040a3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
