<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select</name>
   <tag></tag>
   <elementGuidId>295870ec-8ec3-469e-b131-e128928ed5ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CPClassCodeSearchPopup-CPClassCodeSearchScreen-ClassCodeSearchResultsLV-0-_Select']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gw-action--inner.gw-hasDivider.gw-focus > div.gw-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Select 0001 Boarding and Lodging Houses, Rooming Houses, Fraternities and Sororities - Up to 10 Units&quot;i] >> internal:role=button</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1abe63cf-21a7-446e-b1d0-1a075463250e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-label</value>
      <webElementGuid>13bb9224-4a46-4734-9406-649da19115ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>8ed4e489-3d32-4c53-9a17-8f4e38bce482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>520fbf50-6e6d-4ba7-849d-23867e9606dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CPClassCodeSearchPopup-CPClassCodeSearchScreen-ClassCodeSearchResultsLV-0-_Select&quot;)/div[@class=&quot;gw-action--inner gw-hasDivider gw-focus&quot;]/div[@class=&quot;gw-label&quot;]</value>
      <webElementGuid>38844c77-c363-4739-98c0-20ace7ba20d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CPClassCodeSearchPopup-CPClassCodeSearchScreen-ClassCodeSearchResultsLV-0-_Select']/div/div[2]</value>
      <webElementGuid>cb9a9da4-a847-4be4-ac4d-6292bcb63cfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se'])[4]/following::div[1]</value>
      <webElementGuid>53c63412-9b1e-4b9a-ac93-be6cd4447502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classification'])[4]/following::div[12]</value>
      <webElementGuid>0c427d56-0c4e-42bb-b6c6-d77e217598f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boarding and Lodging Houses, Rooming Houses, Fraternities and Sororities - Up to 10 Units'])[1]/preceding::div[7]</value>
      <webElementGuid>a21df6e5-8100-4cb4-b133-158caadf1820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se'])[5]/preceding::div[12]</value>
      <webElementGuid>4c648fb8-91ed-454f-9b17-f910472a2acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>a873bd39-7227-4fd9-8e1b-933ce59aa0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/div/div[2]</value>
      <webElementGuid>7679446e-46b5-42fd-885f-1321d6b3c2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>dd94d42e-e5df-420f-81a4-bc3cd71c1c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
