<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Search</name>
   <tag></tag>
   <elementGuidId>c5e897cf-11aa-4485-bf30-b5b48b3f258e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>52718eb0-6b76-4e5d-9f83-b7cf7c8006b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search</value>
      <webElementGuid>cab7df61-afdc-4a0f-a8cf-cfdd0b522585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gw-LinkWidget gw-styleTag--InputWidget gw-big-button gw-actionable gw-focus</value>
      <webElementGuid>23413fe4-6809-41f8-8cbd-095d6f236669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-click</name>
      <type>Main</type>
      <value>fireEvent</value>
      <webElementGuid>cca252b6-b33c-481b-af93-8313136f409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-shortcut</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;,&quot;key&quot;:&quot;S&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}</value>
      <webElementGuid>80fc726e-94c0-4d14-9f8e-49e4404aa149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gw-default</name>
      <type>Main</type>
      <value>{&quot;id&quot;:&quot;PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;,&quot;key&quot;:&quot;ENTER&quot;,&quot;op&quot;:&quot;fireevent&quot;,&quot;panel&quot;:&quot;C&quot;}</value>
      <webElementGuid>1cf156e5-fbc3-4123-b15c-d36ed5022e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>aeb7a11b-b460-4efe-abc0-06a8b1f70707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c90c61c8-d4bf-471a-82ff-5abca1543f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>effbc0bc-3e03-4cae-b348-3c2853112b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search&quot;)</value>
      <webElementGuid>171d5972-a454-4a16-abce-5b2cdc2db83d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search']</value>
      <webElementGuid>dfc4e68b-5e33-4d11-b2d1-86d52ff2d03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-searchBtns']/div[2]/div/div</value>
      <webElementGuid>e6d391a3-4fc5-4bc1-935c-0dc8259279d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/following::div[6]</value>
      <webElementGuid>e8ad6b9e-074e-4656-9daf-4860fbf1b460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::div[6]</value>
      <webElementGuid>ce471da0-391b-4a35-b75a-02a22e8656ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='earch']/parent::*</value>
      <webElementGuid>e78965e1-e7ed-4305-879c-aa0fc31cc7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>b525ca3a-9f6e-487c-b498-799cc3cb968f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'PolicyFile_Documents-Policy_DocumentsScreen-Policy_DocumentSearchDV-SearchAndResetInputSet-SearchLinksInputSet-Search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>79d73deb-bf17-4103-95fe-9633dc590fca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
